http:
  host: 'localhost'
  port: 9999
  prefix: 'api'

mariadb:
  host: 'localhost'
  port: 3306
  database: 'lingmengcan-ai'
  username: 'lingmengcan'
  password: 'LMCPassword'
  charset: 'utf8'

mongodb:
  db: 'mongodb://localhost:27017/lingmengcan'

llms:
  embedding_server_url: 'http://127.0.0.1:56391'
  chatglm_6b_server_url: 'http://127.0.0.1:56721'   
  openai_api_key: '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'