http:
  host: 'localhost'
  port: 80
  prefix: 'api'

mariadb:
  host: 'localhost'
  port: 3306
  database: 'lingmengcan'
  username: 'lingmengcan'
  password: 'LMCPassword'
  charset: 'utf8'

mongodb:
  db: 'mongodb://localhost:27017/lingmengcan'