http:
  host: 'localhost'
  port: 80
  prefix: 'api'

db:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  database: 'lingmengcan'
  username: 'lingmengcan'
  password: 'LMCPassword'
  charset: 'utf8'