http:
  host: 'localhost'
  port: 9999
  prefix: 'api'

mariadb:
  host: 'localhost'
  port: 3306
  database: 'lingmengcan-ai'
  username: 'lingmengcan'
  password: '1234556'
  charset: 'utf8'

mongodb:
  db: 'mongodb://localhost:27017/lingmengcan'

chromadb:
  db: 'http://localhost:9000'

files:
  destination: 'upload-files'
